version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./storage:/app/storage

volumes:
  postgres_data: